version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0.0
    steps:
      - checkout
      - run:
          name: Restore packages
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build
